services:
  - type: web
    name: Messenger
    runtime: python
    plan: free
    region: virginia
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT wsgi:application
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/chat.db
      - key: PORT
        value: 8000
      - key: FLASK_DEBUG
        value: "False"
      - key: CORS_ORIGINS
        value: "*"

